project:
  type: website

website:
  title: "Marissa Reitsma, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - cv.qmd
    collapse-below: sm
    right:
      - icon: github
        href: https://github.com/MarissaReitsma
        aria-label: GitHub

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual

